alias l='ls -lkh'
alias la='ls -la'
alias du='du -lkh --max-depth 1'
alias df='df -kTh'
alias mkdir='mkdir -p'
alias rm='rm -I'
alias mv='mv -i'
alias cp='cp -i'
alias root='root -l'
alias ssh='ssh -Y'
alias python='python -t -W ignore::DeprecationWarning'
alias ipython='ipython --colors LightBG'
alias py='ipython'
alias c='clear'
alias cclear='cd && clear'
alias convert300='convert -density 300'
alias R='R --no-save --no-restore-data --quiet'

#the silver surfer with grep colorscheme
alias ag='ag --color-match "1;31" --color-line-number 32 --color-path 35'

#vi is gvim
alias vi='gvim'
